package com.demo.dynamopoc.infrastructure.dynamo

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.demo.dynamopoc.core.book.Book
import com.demo.dynamopoc.core.book.Category
import java.util.*

@DynamoDBTable(tableName = "Book")
class DynamoBook : Book {
    // Partition key
    @get:DynamoDBHashKey(attributeName = "group")
    @DynamoDBTypeConvertedEnum
    override var category: Category?

    // Local secondary index
    @get:DynamoDBAttribute(attributeName = "title")
    @DynamoDBIndexRangeKey(localSecondaryIndexName = "title_idx")
    override var title: String

    // Sorting key
    @get:DynamoDBAttribute(attributeName = "created_date")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    @DynamoDBRangeKey
    override var createdDate: Date?

    @get:DynamoDBAttribute(attributeName = "price")
    override var price: Double

    @get:DynamoDBAttribute(attributeName = "rating")
    override var rating: Int

    constructor() {
        this.title = ""
        this.price = 0.0
        this.rating = 0
        this.category = null
        this.createdDate = null
    }

    constructor(
            title: String,
            group: Category,
            createdDate: Date,
            price: Double,
            rating: Int
    ) {
        this.title = title
        this.price = price
        this.rating = rating
        this.category = group
        this.createdDate = createdDate
    }
}